### ISSUE TITLE
problem with git clone

### ISSUE THREAD

**Issue by inpolonsky** [AER-RC/monoRTM#1]
I I run:
git clone --recursive git@github.com:AER-RC/monoRTM.git

I have the following messages

Cloning into 'monoRTM'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

if I run:
git clone --recursive https://github.com/AER-RC/monoRTM.git
Cloning into 'monoRTM'...
remote: Enumerating objects: 1545, done.
remote: Counting objects: 100% (1545/1545), done.
remote: Compressing objects: 100% (624/624), done.
remote: Total 1545 (delta 908), reused 1494 (delta 867), pack-reused 0
Receiving objects: 100% (1545/1545), 1.63 MiB | 0 bytes/s, done.
Resolving deltas: 100% (908/908), done.
Submodule 'cross-sections' (git@github.com:AER-RC/cross-sections.git) registered for path 'cross-sections'
Cloning into 'cross-sections'...
Warning: Permanently added the RSA host key for IP address '140.82.114.3' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:AER-RC/cross-sections.git' into submodule path 'cross-sections' failed

**Comment by pernak18** [comment]
@inpolonsky i cannot reproduce your SSH error on the top-level clone of monoRTM, and i have had two others report they also have no issues.

HTTPS, however, is a known problem because of how i committed `.git/config`, so i'll keep this issue up and look into how i can make the clone of submodules more flexible regarding which protocol to use.

**Comment by inpolonsky** [comment]
@pernak18 Don't worry I found my way around. So if it works, then something inherently wrong with my ssh setup. I am planning to move to another version of Linux (from Centos 7) , which may eliminate all the problems.
