### ISSUE TITLE
netcdf_helper_mod.f90 seems superfluous and confuses the make system

### ISSUE THREAD

**Issue by BenjaminTJohnson** [AER-RC/monoRTM#3]
The file "netcdf_helper_mod.f90" is (almost) a copy of "netcdf_helper_mod.F90", but confuses the make system because it has a preprocessor directive, but the lower-case f90 file ignores it, and still tries to look for netcdf even if you're trying to make without it.  Simply removing the file allowed make to find the correct upper-case F90 file, and the build completed without an issue.

**Comment by kcadyper** [comment]
Rick, how can we remove this file?

**Comment by pernak18** [comment]
done with https://github.com/AER-RC/monoRTM/commit/634f3af1f0f1f5fecc2bb2cbf90d1bfc20f42d49
